export { default as Tabs } from "./main/tabs"
export { default as Content } from "./main/content"
export { default as ListItems } from "./main/listitem"
export { default as DetailList } from "./main-details/detail-list"
export { default as Card } from "./main-details/card"
